def normalizar_texto(texto):
    """Normaliza texto para comparación"""
    if texto is None:
        return ""
    return str(texto).lower().strip()

def nombre_a_numero(nombre):
    """Convierte nombre de animal a número - Guácharo Activo (87 animales)"""
    mapa = {
        # 0-9
        "delfin": 0, "delfín": 0,
        "carnero": 1,
        "toro": 2,
        "ciempies": 3, "ciempiés": 3,
        "alacrán": 4, "alacran": 4,
        "león": 5, "leon": 5,
        "rana": 6,
        "perico": 7,
        "ratón": 8, "raton": 8,
        "águila": 9, "aguila": 9,
        # 10-19
        "tigre": 10,
        "gato": 11,
        "caballo": 12,
        "mono": 13,
        "paloma": 14,
        "zorro": 15,
        "oso": 16,
        "pavo": 17,
        "burro": 18,
        "chivo": 19,
        # 20-29
        "cochino": 20,
        "gallo": 21,
        "camello": 22,
        "cebra": 23,
        "iguana": 24,
        "gallina": 25,
        "vaca": 26,
        "perro": 27,
        "zamuro": 28,
        "elefante": 29,
        # 30-39
        "caimán": 30, "caiman": 30,
        "lapa": 31,
        "ardilla": 32,
        "pescado": 33,
        "venado": 34,
        "jirafa": 35,
        "culebra": 36,
        "tortuga": 37,
        "lechuza": 38,
        "chigüire": 39, "chiguire": 39,
        # 40-49
        "gorila": 40,
        "canguro": 41,
        "puercoespín": 42, "puercoespin": 42,
        "jorobado": 43,
        "garza": 44,
        "ballena": 45,
        "puma": 46,
        "pavo real": 47,
        "hormiga": 48,
        "oso hormiguero": 49,
        # 50-59
        "pereza": 50,
        "canario": 51,
        "cotorra": 52,
        "pulpo": 53,
        "caracol": 54,
        "grillo": 55,
        "mapache": 56,
        "tiburón": 57, "tiburon": 57,
        "pato": 58,
        "murciélago": 59, "murcielago": 59,
        # 60-69
        "nutria": 60,
        "camaleón": 61, "camaleon": 61,
        "rinoceronte": 62,
        "cachicamo": 63,
        "gavilán": 64, "gavilan": 64,
        "araña": 65, "arana": 65,
        "sapo": 66,
        "comadreja": 67,
        "conejo": 68,
        "serpiente": 69,
        # 70-75
        "guacamaya": 70,
        "cocodrilo": 71,
        "hipopótamo": 72, "hipopotamo": 72,
        "pantera": 73,
        "cuervo": 74,
        "búho": 75, "buho": 75,
        # NUEVOS ANIMALES AGREGADOS (76-85)
        "pelícano": 76, "pelicano": 76,
        "guácharo": 77, "guacharo": 77,
        "búfalo": 78, "bufalo": 78,
        "tucán": 79, "tucan": 79,
        "mariposa": 80,
        "avestruz": 81,
        "turpial": 82,
        "cangrejo": 83,
        "bisonte": 84,
        "lobo": 85,
        # Especial
        "00": 100
    }
    if nombre is None:
        return None
    texto_norm = normalizar_texto(nombre)
    return mapa.get(texto_norm)

def numero_a_nombre(numero):
    """Convierte número a nombre de animal - Guácharo Activo (77 animales)"""
    mapa = {
        0: "Delfín",
        1: "Carnero",
        2: "Toro",
        3: "Ciempiés",
        4: "Alacrán",
        5: "León",
        6: "Rana",
        7: "Perico",
        8: "Ratón",
        9: "Águila",
        10: "Tigre",
        11: "Gato",
        12: "Caballo",
        13: "Mono",
        14: "Paloma",
        15: "Zorro",
        16: "Oso",
        17: "Pavo",
        18: "Burro",
        19: "Chivo",
        20: "Cochino",
        21: "Gallo",
        22: "Camello",
        23: "Cebra",
        24: "Iguana",
        25: "Gallina",
        26: "Vaca",
        27: "Perro",
        28: "Zamuro",
        29: "Elefante",
        30: "Caimán",
        31: "Lapa",
        32: "Ardilla",
        33: "Pescado",
        34: "Venado",
        35: "Jirafa",
        36: "Culebra",
        37: "Tortuga",
        38: "Lechuza",
        39: "Chigüire",
        40: "Gorila",  # Actualizado desde scraping
        41: "Canguro",
        42: "Puercoespín",  # Actualizado desde scraping
        43: "Jorobado",
        44: "Garza",
        45: "Ballena",
        46: "Puma",
        47: "Pavo Real",
        48: "Hormiga",
        49: "Oso Hormiguero",
        50: "Pereza",
        51: "Canario",
        52: "Cotorra",
        53: "Pulpo",
        54: "Caracol",
        55: "Grillo",
        56: "Mapache",
        57: "Tiburón",
        58: "Pato",
        59: "Murciélago",
        60: "Nutria",
        61: "Camaleón",
        62: "Rinoceronte",
        63: "Cachicamo",
        64: "Gavilán",
        65: "Araña",
        66: "Sapo",
        67: "Comadreja",
        68: "Conejo",
        69: "Serpiente",
        70: "Guacamaya",
        71: "Cocodrilo",
        72: "Hipopótamo",
        73: "Pantera",
        74: "Cuervo",
        75: "Búho",
        100: "Ballena (00)"
    }
    return mapa.get(numero, f"Animal-{numero}")
